=== Amit-Thawait/mingle/mingle/help/topics/mingle_help.dtd
<!--
/*
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
*/
			INDEX - for building the left nav control
-->
<!ELEMENT index (#PCDATA | entry)* >
<!ELEMENT entry (#PCDATA | entry)* >
<!ATTLIST entry reference CDATA #REQUIRED >

<!-- 
            TAGS WHICH ARE USED TO FORMAT THE HELP PAGES
-->
<!ELEMENT chapter (#PCDATA | topic | section)* >
<!ATTLIST chapter title CDATA #REQUIRED>

<!ELEMENT topic (#PCDATA | section | p | note | hint | warning | bullets | steps | markup_reference | screenshot | todo | img | example | config | code | markup | formula | api_reference | table)*>
<!ATTLIST topic title CDATA #REQUIRED>
<!ATTLIST topic file CDATA #IMPLIED>
<!ATTLIST topic collapsed CDATA #IMPLIED>

<!ELEMENT section (#PCDATA | subsection | p | note | hint | warning | bullets | steps | markup_reference | screenshot | todo | img | example | config | code | markup | formula | api_reference | table)*>
<!ATTLIST section title CDATA #REQUIRED>
<!ATTLIST section file CDATA #IMPLIED >
<!ATTLIST section collapsed CDATA #IMPLIED>

<!ELEMENT subsection (#PCDATA | p | note | hint | warning | bullets | steps | markup_reference | api_reference |screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | table)*>
<!ATTLIST subsection title CDATA #REQUIRED>
<!ATTLIST subsection file CDATA #IMPLIED >
<!ATTLIST subsection collapsed CDATA #IMPLIED>

<!ELEMENT table (#PCDATA | group | header-row | row )* >
<!ATTLIST table caption CDATA #REQUIRED >

<!ELEMENT group (#PCDATA | row )* >
<!ATTLIST group title CDATA #REQUIRED >
<!ATTLIST group col-headers CDATA #IMPLIED >

<!ELEMENT header-row (#PCDATA | col-header)*>
<!ELEMENT col-header (#PCDATA) >

<!ELEMENT row (#PCDATA | label | col)* >
<!ELEMENT label (#PCDATA) >
<!ELEMENT col (#PCDATA | p | bullets | steps | screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | filter )* >

<!-- markup_reference - is a reference entry to explain some markup.
        it contains a title to explain the intent,
        a markup element to show the markup,
        a preview to show the outcome of the markup,
        a note (optional),
        an icon (optional) - e.g. the toolbar icon for example that will insert the markup -->
<!ELEMENT markup_reference ( markup | preview | note | icon | todo)*>
<!ATTLIST markup_reference title CDATA #REQUIRED>

<!ELEMENT api_reference ( code | preview | note | bullets )* >
<!ATTLIST api_reference title CDATA #REQUIRED>

<!ELEMENT steps ( p | item+)*>
<!ATTLIST steps title CDATA #IMPLIED>

<!ELEMENT bullets ( p | item+)*>
<!ATTLIST bullets title CDATA #IMPLIED>

<!ELEMENT item (#PCDATA | p | note | hint | warning | bullets | steps | screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | filter )*>

<!ELEMENT screenshot (#PCDATA)>
<!ATTLIST screenshot alttext CDATA #REQUIRED>
<!ATTLIST screenshot src CDATA #REQUIRED>
<!ATTLIST screenshot caption CDATA #IMPLIED>

<!ELEMENT cref (#PCDATA)>
<!ATTLIST cref topic CDATA #REQUIRED>

<!ELEMENT strong (#PCDATA | todo | link | button | sidebar-button | cref | cmd)*>

<!ELEMENT p (#PCDATA | exref | strong | cref | img | screenshot | video | todo | term | link | button | sidebar-button | tab | cmd | code | path | markup | url | subst | filter | formula | config | table)*>

<!ELEMENT exref (#PCDATA)>
<!ATTLIST exref url CDATA #REQUIRED>

<!ELEMENT hint (#PCDATA | p | strong | cref | exref | todo | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula | bullets)*>
<!ELEMENT note (#PCDATA | p | strong | cref | exref | todo | example | bullets | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula)*>
<!ELEMENT warning (#PCDATA | p | strong | cref | exref | todo | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula | bullets)*>

<!ELEMENT example (#PCDATA | p | strong | cref | exref | todo | bullets | steps | img | screenshot | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula)*>
<!ATTLIST example title CDATA #IMPLIED>

<!ELEMENT img (#PCDATA | clickaction)*>
<!ATTLIST img alttext CDATA #REQUIRED>
<!ATTLIST img src CDATA #REQUIRED>
<!ATTLIST img url CDATA #IMPLIED>

<!-- icon refers to a UI element, and holds a picture of that element -->
<!ELEMENT icon (#PCDATA)>
<!ATTLIST icon alttext CDATA #REQUIRED>
<!ATTLIST icon src CDATA #REQUIRED>

<!-- clickaction is used to map links to clickable areas inside an image -->
<!ELEMENT clickaction (#PCDATA | exref | cref)*>
<!ATTLIST clickaction align CDATA #REQUIRED>
<!ATTLIST clickaction unit CDATA #REQUIRED>
<!ATTLIST clickaction height CDATA #REQUIRED>
<!ATTLIST clickaction width CDATA #REQUIRED>
<!ATTLIST clickaction offset CDATA #IMPLIED>

<!-- video refers to a link to some video content, allows decoration with an appropriate icon -->
<!ELEMENT video (#PCDATA)*>
<!ATTLIST video url CDATA #REQUIRED>

<!-- cmd: indicates that the enclosed text is an operating system command -->
<!ELEMENT cmd (#PCDATA | p)*>
<!ATTLIST cmd os CDATA #IMPLIED>
<!-- config: indicates that the enclosed text is a piece of application configuration -->
<!ELEMENT config (#PCDATA)*>
<!-- code: indicates that the enclosed text is a piece of programming language source code -->
<!ELEMENT code (#PCDATA | strong | cref | subst)*>
<!ATTLIST code lang CDATA #IMPLIED>
<!-- path: indicates that the enclosed text is a path to a file -->
<!ELEMENT path (#PCDATA | subst)*>
<!-- markup: indicates that the enclosed text is markup -->
<!ELEMENT markup (#PCDATA | subst | todo)*>
<!-- preview: indicates that the enclosed text is preview of markup -->
<!ELEMENT preview (#PCDATA | p | img | screenshot | todo | code)* >
<!-- url: indicates that the enclosed text is an url - note this is a formatting tag, the url should not be navigable -->
<!ELEMENT url (#PCDATA | subst)*>
<!-- subst: indicates that the enclosed text should be substituted with another value (or removed) -->
<!ELEMENT subst (#PCDATA) >
<!-- todo - indicates that something need to be changed or added to the content at this point, should not appear in final help output -->
<!ELEMENT todo (#PCDATA)*>
<!-- term: indicates that the enclosed text should appear in the glossary -->
<!ELEMENT term (#PCDATA)>
<!-- formula: indicates that the enclosed text is a formula -->
<!ELEMENT formula (#PCDATA | subst | todo)*>

<!-- 
        TAGS THAT REFER TO APPLICATION WIDGETS
-->
<!-- link: indicates that the enclosed text appears as a link in the application -->
<!ELEMENT link (#PCDATA)>
<!-- button: indicates that the enclosed text appears as a button in the application -->
<!ELEMENT button (#PCDATA)>
<!-- sidebar-button: indicates that the enclosed text appears as a sidebar button in the application -->
<!ELEMENT sidebar-button (#PCDATA)>
<!-- tab: indicates that the enclosed text appears as a tab in the application -->
<!ELEMENT tab (#PCDATA)>
<!-- filter: indicates that the enclosed text is a mingle filter condition -->
<!ELEMENT filter (#PCDATA) >

=== Amit-Thawait/mingle/mingle/help/topics/user_roles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE topic SYSTEM "mingle_help.dtd">
<topic title="User roles"><section title="Introduction..." collapsed = 'false'> <p> User roles
determine what users can see and do in Mingle.</p> <hint>You must <cref
topic="creating_user_profiles">register users in Mingle</cref> before you can
assign any user roles. Before registered users can view projects, you must set
them up as project team members (and/or project administrators).</hint>
<bullets title="There are six types of user who may interact with Mingle:">
    <item>Mingle administrator</item>

    <item>Project administrator</item>

    <item>Project team member</item>

    <item>Read only project team member</item>

    <item>Non-project member</item>

    <item>Anonymous user</item>
  </bullets> <p>At the Mingle level, users can either have a full team member role, a light team member role, 
be a Mingle administrator or be anonymous. Mingle administrators have full,
unrestricted access to Mingle and all Mingle projects. Mingle team members (either full or light users) must be
granted access to specific projects (either as a project administrators or
project team members) before they can access any Mingle data. Those users without
any project permissions are either logged in non-project members or anonymous users. They may be able to access projects
if <cref topic="project_settings_page">anonymous access has been enabled</cref>. </p> </section> 

<section title="Mingle administrator" id="mingle_administrator" collapsed = 'true'> <p>Mingle administrators have full control over
an installed version of Mingle. By default, the person who installs Mingle is
the Mingle administrator. This person may add other Mingle administrators as
required.</p> <bullets title="Mingle administrators can:">
    <item>access all projects (regardless of whether they are project
    members)</item>

    <item>create, edit or delete projects</item>

    <item>import/export projects</item>

    <item>edit user details</item>

    <item>create/edit/delete cards and pages</item>

    <item>add, edit or delete any project properties</item>

    <item>add/remove team members from project</item>

    <item>manage tags</item>

    <item>create/edit/delete card transitions</item>

    <item>Integrate the Mingle instance with a Slack team</item>

    <item>manage saved views</item>
  </bullets> <hint>There is nothing a Mingle administrator cannot do.</hint>
</section>

<section title="Project administrator" id="project_administrator" collapsed = 'true'> <p>Project administrators
must be setup by a Mingle administrator. Mingle administrators are usually
also project administrators for one or more projects.</p> <bullets
    title="Project administrators can:">
    <item>access only those projects to which they have permission</item>

    <item>import/export their projects</item>

    <item>add/remove team members from his/her project(s)</item>

    <item>manage tags</item>

    <item>create/edit/delete cards and pages</item>

    <item>set card transitions</item>

    <item>manage saved views</item>

    <item>add, edit or delete any project properties</item>

    <item>Integrate the project with a Slack channel</item>

  </bullets> <bullets title="Project administrators cannot:">
    <item>add new users to Mingle</item>

    <item>access projects where they aren't members</item>

    <item>create or delete projects</item>
  </bullets> 

</section>

<section title="Project team member" id="project_member" collapsed = 'true'> <p>Project
members must be setup by Mingle administrators or project administrators.
Project team members may be read only team members on other projects. Most Mingle users are assigned project member roles.</p> <bullets
    title="Project team members can:">
    <item>access only those projects to which they have permission</item>

    <item>create and edit cards and pages</item>
 
    <item>export projects</item>

    <item>create and access saved views</item>

    <item>edit their own profile</item>

    <item>view, set and update property values</item>
    
    <item>view and use project card transitions</item>

    <item>view team members</item>

  </bullets> 

<bullets title="Project team members cannot:">
   
    <item>access projects where they aren't members</item>

    <item>delete cards and pages</item>

    <item>add, edit or delete project properties</item>

    <item>create, edit or delete card transitions</item>

    <item>add or edit team members</item>
  </bullets> </section> 

<section title="Read only project team member" id="read_only_project_team_member" collapsed = 'true'>
<p>Read only project team members must be setup by Mingle administrators or
project administrators. Read only members are project team members who can
view project data but cannot add, edit or delete any project data. Read only team members may be full team members or project administrators on other projects. </p>
<bullets title="Read only project team members can:">
    <item>access only those projects to which they have permission</item>

    <item>view cards and pages</item>

    <item>export projects</item>

    <item>access favorite views</item>

    <item>view project history</item>

    <item>edit their own profile</item>
  </bullets> <bullets title="Read only project team members cannot:">
    <item>access projects where they aren't members</item>

    <item>create/edit/delete cards and pages</item>

    <item>post murmurs on cards</item>

    <item>add, edit or delete project properties values</item>

    <item>drag and drop cards in grid or tree views</item>

    <item>create favorite views</item>

</bullets> </section> 

<section title="Non-project member" collapsed = 'true'> <p>A non-project
member is anybody who is setup as a Mingle user, but who has not been given
access to a project. They can sign in to Mingle, but cannot access any
projects. They will see projects that have been set to allow logged in users to request membership on the all projects page and can request membership to those projects. Once they are added to a project team they will become a project team member.</p> </section>

<section title="Anonymous user" collapsed = 'true'>
<p>An
anonymous (anon) user is a user who can access a project without logging into
Mingle or without being a project team member. Anonymous access is enabled at
the project level. If a project has anonymous access enabled, users may view
the project without logging in.  </p>

<note> Anonymous access to projects is only available on Mingle instances that are have anonymous access enabled <cref topic="mingle_licenses">licenses</cref>.</note>

</section>

<section title="Full users and light users" id="full_users_and_light_users" collapsed = 'true'>
<p>Mingle users can be full users or light users. Full or light access must be assigned by a Mingle administrator. Full and light users can be assigned access to projects by Mingle or project administrators. Mingle administrators are full users. Full users may also be Project administrators, Project team members, Read only team members or a combination of different roles on different projects.  Light users can only be assigned a Read only project team member role on projects they are assigned to. Light users cannot be project team members, Mingle or project administrators. </p>

<hint>The number of full and light users allowed per Mingle instance is determined by the registered <cref topic="mingle_licenses">license</cref>.</hint>

 </section>


<section title="Also see..."> <bullets>
    <item><cref topic="creating_user_profiles">Creating user
    profiles</cref></item>

    <item><cref topic="managing_project_team_members">Managing project team
    members</cref></item>

    <item><cref topic="customizing_projects">Customizing projects</cref></item>
    <item><cref topic="mingle_licenses">Mingle licenses</cref></item>
    </bullets>
</section></topic>

=== Amit-Thawait/mingle/mingle/help/topics/configuring_ssl_access.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE chapter SYSTEM "mingle_help.dtd">
<topic title="Configuring SSL Access" id="configure_ssl">
  <p>You can turn on HTTPS access by configuring a few properties in mingle.properties as follows:</p>
  <markup>
-Dmingle.ssl.port=8443
-Dmingle.ssl.keystore=/PATH/TO/KEYSTORE
-Dmingle.ssl.keystorePassword=PASSWORD_TO_ACCESS_KEYSTORE
-Dmingle.ssl.keyPassword=KEY_PASSPHRASE</markup>
  <p>You can have both HTTP and HTTPS enabled for Mingle by setting proper values for both the -Dmingle.port property and the entire -Dmingle.ssl.* section.</p>
  <hint>Mingle 15.1 and above does not allow you to set both HTTP and HTTPS concurrently.</hint>
  <p>You can disable HTTP or HTTPS by not setting either of -Dmingle.port or -Dmingle.ssl.port.</p>
  <p>If neither -Dmingle.port nor -Dmingle.ssl.port is given, a default of "8080" for -Dmingle.port will be used.</p>
  <p>Your keystore (mingle.ssl.keystore) is a file in which keys and certificates are stored. Mingle requires access to it to provide secure HTTPS connections. Your certificate will need to be imported into this keystore. You can find more information on creating and managing a keystore <exref url="http://download.oracle.com/javase/6/docs/technotes/tools/windows/keytool.html">here</exref>.</p>
  <p>We recommend storing your keystore in a directory outside of Mingle's install folder so that the keystore does not need to be moved during subsequent Mingle upgrades.</p>
  <p>Your keystore file is password protected, so you need to provide your keystore password as mingle.ssl.keystorePassword.</p>
  <p>The mingle.ssl.keyPassword entry should contain your key's password.</p>
  <hint>These properties are only used to configure the SSL port to which Mingle binds on its host machine. Be sure to also configure -Dmingle.siteURL (see <cref topic="advanced_mingle_configuration">advanced configuration</cref>) to match the new HTTPS URL.</hint>
</topic>

=== Amit-Thawait/mingle/mingle/help/topics/tags_page.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE topic SYSTEM "mingle_help.dtd">
<topic title="Tags page">
	<section title="What you can do on this page">
		<p>
			The Tags page shows all tags applied to cards or pages in Mingle. 
			From here you can see which tags are currently used in the project and those that are no longer being used. 
			You can also delete tags or edit tag names from this page.
		</p>
		<bullets>
			<item><cref topic="creating_tags_for_cards_or_wiki_pages">Creating tags for cards or wiki pages</cref></item>
			<item><cref topic="managing_tags">Managing tags</cref></item>
		</bullets>
	</section>
	<section title="Also see...">
		<bullets>
			<item><cref topic="working_with_tags">Working with tags</cref></item>
			<item><cref topic="customizing_projects">Customizing projects</cref></item>
		</bullets>
	</section>
</topic>

=== Amit-Thawait/mingle/mingle/help/topics/tree_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE subsection SYSTEM "mingle_help.dtd">
<section title="Using the tree filter">
	<p>The tree filter is similar to the
<cref topic="filter_list_by_component">list view card filter</cref>, except
that it allows you to set filter conditions separately for each card type in
the tree.</p>
	<screenshot alttext="card tree - tree filter" src="resources/images/card_trees_tree_view_tree_filter.png"/>
	<example title="Some tree filter examples">
		<bullets title="User selects to view cards with Release-size > 30 and Iteration-priority = high. The following cards are displayed">
			<item>All Release cards with size &gt; 30</item>
			<item>All high priority Iteration cards within releases that have size
    &gt; 30</item>
			<item>All stories belonging to the above iterations</item>
		</bullets>
		<bullets title="User selects to view cards with Story Priority = High">
			<item>This would display all release cards and all iteration cards</item>
			<item>Only story cards having priority = High would be displayed</item>
			<item>If a Release or Iteration does not contain a story with priority set
    to High, it is still displayed, but its child stories are not</item>
		</bullets>
		<bullets title="If filter criteria is defined as Release = R1">
			<item>R1 is displayed</item>
			<item>Only iterations and stories which belong to R1 will be
    displayed</item>
		</bullets>
	</example>
	<p>You can choose to hide all cards of a given type in
the tree by checking the box next to the card type in the <strong>Do
not</strong> show section at the top of the filter.</p>
	<steps>
		<item>
			<p><strong>To add a new filter condition</strong>, click on the
    <link>Add a filter</link> link. A new row will be inserted into the filter
    control.</p>
			<screenshot alttext="New filter condition" src="resources/images/new_tree_filter_condition.png"/>
		</item>
		<item>
			<p><strong>Choose a property</strong> by clicking on the
    <link>(select...)</link> link. You will be able to choose any property
    which is associated with the card type.</p>
		</item>
		<item>
			<p><strong>Choose a comparison operator</strong> by clicking on the
    <link>is</link> link. The options available will depend on what is
    applicable to the property you selected in the step above. You won't be
    able to select anything except the default until you've selected a
    property, because the allowable values are dependent on the property
    selected.</p>
			<bullets title="Full list of comparison operators">
				<item><strong>is</strong> - the default operator; will restrict the
        property to only the value specified.</item>
				<item><strong>is not</strong> - will restrict the property to only
        values other than the one specified.</item>
				<item><strong>is less than</strong> - shown when the property is
        ordered. Will restrict the property to values which are strictly less
        than the specified value. Does not include cards having the property
        value equal to the specified value.</item>
				<item><strong>is greater than</strong> - shown when the property is
        ordered. Will restrict the property to values which are strictly
        greater than the specified value. Does not include cards having the
        property value equal to the specified value.</item>
				<item><strong>is before</strong> - shown when the property is a date,
        equivalent to <strong>is less than</strong>. Does not include cards
        having the property value equal to the specified date.</item>
				<item><strong>is after</strong> - shown when the property is a date,
        equivalent to <strong>is greater than</strong>. Does not include cards
        having the property value equal to the specified date.</item>
			</bullets>
			<note>
				<bullets>
					<item>Properties can have a natural order, such as numbers or dates -
        in this case that natural ordering is used to resolve 'is less/greater
        than' conditions.</item>
					<item>Managed properties, where the allowable values are specified in
        a list - use the sort order of the list to resolve 'is less/greater
        than' conditions. <todo>the rule is that the list is sorted in
        ascending order from top to bottom, should add graphics here to
        explain</todo></item>
				</bullets>
			</note>
		</item>
		<item>
			<p><strong>Choose a value</strong> by clicking on the
    <link>(any)</link> link. The options available will depend on what is
    applicable to the property you selected in the step above. You won't be
    able to select anything except the default until you've selected a
    property, because the allowable values are dependent on the property
    selected.</p>
			<note>
				<p>There are several special values which can appear
    here:</p>
				<bullets>
					<item><strong>(any)</strong> - Specifies cards having any value for
        the selected property. Available for operators <strong>is</strong> and
        <strong>is not</strong>. This is the same as having no condition for
        the property at all.</item>
					<item><strong>(not set)</strong> - Specifies cards which have no value
        set for the property. Available for operators <strong>is</strong> and
        <strong>is not</strong>. This is analogous to the 'null' term in SQL.
        It is not available for mandatory Mingle card properties such as
        Type.</item>
					<item><strong>(current user)</strong> - Specifies cards which have the
        currently logged in user assigned to the selected property. Available
        for operators <strong>is</strong> and <strong>is not</strong>.
        Available for properties which take Mingle users as values.</item>
					<item><strong>(today)</strong> - Specifies cards which have the
        current date assigned to the selected property. Available for
        operators <strong>is</strong>, <strong>is not</strong>, <strong>is
        before</strong>, <strong>is after</strong>. Available for date
        properties.</item>
				</bullets>
			</note>
			<bullets title="The available values depend on the data type of the property you selected">
				<item>if you selected the <strong>Type property</strong>, then you
        will be presented with the list of all card types and the special
        value (any).</item>
				<item>if you selected a <strong>Managed List property</strong>, then you
        will be presented with the list of all values that have been specified
        in the managed list and the special values (any), (not set).</item>
				<item>if you selected a <strong>Date</strong>, then you will be presented
        with a calendar widget that will allow you to select a date, as well
        as the special values (any), (not set) and (today).</item>
				<item>if you selected a <strong>Team member property</strong>, then you
        will be presented with a list of the current team members, as well as
        the special values (any), (not set) and (current user).</item>
			</bullets>
		</item>
		<item>Your new filter condition will be applied as soon as you've selected
    a value, and you should see the results reflected in the cards displayed
    in the view.</item>
		<item>You can optionally filter the tree by specifying tags. Click on the
    <link>Add tags</link> link, type in the tags separated by commas, and
    click the <button>Add tags</button> button. Only cards which have all of
    the specified tags will be displayed.</item>
		<item>
			<p><strong>To remove a filter condition</strong>, simply click on
    the <screenshot alttext="Delete filter condition button" src="resources/images/delete_filter_condition_button.png"/>
    next to the condition you want to remove. Again, the effect of removing
    the condition will immediately be reflected in the view.</p>
		</item>
	</steps>
</section>
