=== Amit-Thawait/mingle/mingle/help/topics/mingle_help.dtd
<!--
/*
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
*/
			INDEX - for building the left nav control
-->
<!ELEMENT index (#PCDATA | entry)* >
<!ELEMENT entry (#PCDATA | entry)* >
<!ATTLIST entry reference CDATA #REQUIRED >

<!-- 
            TAGS WHICH ARE USED TO FORMAT THE HELP PAGES
-->
<!ELEMENT chapter (#PCDATA | topic | section)* >
<!ATTLIST chapter title CDATA #REQUIRED>

<!ELEMENT topic (#PCDATA | section | p | note | hint | warning | bullets | steps | markup_reference | screenshot | todo | img | example | config | code | markup | formula | api_reference | table)*>
<!ATTLIST topic title CDATA #REQUIRED>
<!ATTLIST topic file CDATA #IMPLIED>
<!ATTLIST topic collapsed CDATA #IMPLIED>

<!ELEMENT section (#PCDATA | subsection | p | note | hint | warning | bullets | steps | markup_reference | screenshot | todo | img | example | config | code | markup | formula | api_reference | table)*>
<!ATTLIST section title CDATA #REQUIRED>
<!ATTLIST section file CDATA #IMPLIED >
<!ATTLIST section collapsed CDATA #IMPLIED>

<!ELEMENT subsection (#PCDATA | p | note | hint | warning | bullets | steps | markup_reference | api_reference |screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | table)*>
<!ATTLIST subsection title CDATA #REQUIRED>
<!ATTLIST subsection file CDATA #IMPLIED >
<!ATTLIST subsection collapsed CDATA #IMPLIED>

<!ELEMENT table (#PCDATA | group | header-row | row )* >
<!ATTLIST table caption CDATA #REQUIRED >

<!ELEMENT group (#PCDATA | row )* >
<!ATTLIST group title CDATA #REQUIRED >
<!ATTLIST group col-headers CDATA #IMPLIED >

<!ELEMENT header-row (#PCDATA | col-header)*>
<!ELEMENT col-header (#PCDATA) >

<!ELEMENT row (#PCDATA | label | col)* >
<!ELEMENT label (#PCDATA) >
<!ELEMENT col (#PCDATA | p | bullets | steps | screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | filter )* >

<!-- markup_reference - is a reference entry to explain some markup.
        it contains a title to explain the intent,
        a markup element to show the markup,
        a preview to show the outcome of the markup,
        a note (optional),
        an icon (optional) - e.g. the toolbar icon for example that will insert the markup -->
<!ELEMENT markup_reference ( markup | preview | note | icon | todo)*>
<!ATTLIST markup_reference title CDATA #REQUIRED>

<!ELEMENT api_reference ( code | preview | note | bullets )* >
<!ATTLIST api_reference title CDATA #REQUIRED>

<!ELEMENT steps ( p | item+)*>
<!ATTLIST steps title CDATA #IMPLIED>

<!ELEMENT bullets ( p | item+)*>
<!ATTLIST bullets title CDATA #IMPLIED>

<!ELEMENT item (#PCDATA | p | note | hint | warning | bullets | steps | screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | filter )*>

<!ELEMENT screenshot (#PCDATA)>
<!ATTLIST screenshot alttext CDATA #REQUIRED>
<!ATTLIST screenshot src CDATA #REQUIRED>
<!ATTLIST screenshot caption CDATA #IMPLIED>

<!ELEMENT cref (#PCDATA)>
<!ATTLIST cref topic CDATA #REQUIRED>

<!ELEMENT strong (#PCDATA | todo | link | button | sidebar-button | cref | cmd)*>

<!ELEMENT p (#PCDATA | exref | strong | cref | img | screenshot | video | todo | term | link | button | sidebar-button | tab | cmd | code | path | markup | url | subst | filter | formula | config | table)*>

<!ELEMENT exref (#PCDATA)>
<!ATTLIST exref url CDATA #REQUIRED>

<!ELEMENT hint (#PCDATA | p | strong | cref | exref | todo | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula | bullets)*>
<!ELEMENT note (#PCDATA | p | strong | cref | exref | todo | example | bullets | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula)*>
<!ELEMENT warning (#PCDATA | p | strong | cref | exref | todo | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula | bullets)*>

<!ELEMENT example (#PCDATA | p | strong | cref | exref | todo | bullets | steps | img | screenshot | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula)*>
<!ATTLIST example title CDATA #IMPLIED>

<!ELEMENT img (#PCDATA | clickaction)*>
<!ATTLIST img alttext CDATA #REQUIRED>
<!ATTLIST img src CDATA #REQUIRED>
<!ATTLIST img url CDATA #IMPLIED>

<!-- icon refers to a UI element, and holds a picture of that element -->
<!ELEMENT icon (#PCDATA)>
<!ATTLIST icon alttext CDATA #REQUIRED>
<!ATTLIST icon src CDATA #REQUIRED>

<!-- clickaction is used to map links to clickable areas inside an image -->
<!ELEMENT clickaction (#PCDATA | exref | cref)*>
<!ATTLIST clickaction align CDATA #REQUIRED>
<!ATTLIST clickaction unit CDATA #REQUIRED>
<!ATTLIST clickaction height CDATA #REQUIRED>
<!ATTLIST clickaction width CDATA #REQUIRED>
<!ATTLIST clickaction offset CDATA #IMPLIED>

<!-- video refers to a link to some video content, allows decoration with an appropriate icon -->
<!ELEMENT video (#PCDATA)*>
<!ATTLIST video url CDATA #REQUIRED>

<!-- cmd: indicates that the enclosed text is an operating system command -->
<!ELEMENT cmd (#PCDATA | p)*>
<!ATTLIST cmd os CDATA #IMPLIED>
<!-- config: indicates that the enclosed text is a piece of application configuration -->
<!ELEMENT config (#PCDATA)*>
<!-- code: indicates that the enclosed text is a piece of programming language source code -->
<!ELEMENT code (#PCDATA | strong | cref | subst)*>
<!ATTLIST code lang CDATA #IMPLIED>
<!-- path: indicates that the enclosed text is a path to a file -->
<!ELEMENT path (#PCDATA | subst)*>
<!-- markup: indicates that the enclosed text is markup -->
<!ELEMENT markup (#PCDATA | subst | todo)*>
<!-- preview: indicates that the enclosed text is preview of markup -->
<!ELEMENT preview (#PCDATA | p | img | screenshot | todo | code)* >
<!-- url: indicates that the enclosed text is an url - note this is a formatting tag, the url should not be navigable -->
<!ELEMENT url (#PCDATA | subst)*>
<!-- subst: indicates that the enclosed text should be substituted with another value (or removed) -->
<!ELEMENT subst (#PCDATA) >
<!-- todo - indicates that something need to be changed or added to the content at this point, should not appear in final help output -->
<!ELEMENT todo (#PCDATA)*>
<!-- term: indicates that the enclosed text should appear in the glossary -->
<!ELEMENT term (#PCDATA)>
<!-- formula: indicates that the enclosed text is a formula -->
<!ELEMENT formula (#PCDATA | subst | todo)*>

<!-- 
        TAGS THAT REFER TO APPLICATION WIDGETS
-->
<!-- link: indicates that the enclosed text appears as a link in the application -->
<!ELEMENT link (#PCDATA)>
<!-- button: indicates that the enclosed text appears as a button in the application -->
<!ELEMENT button (#PCDATA)>
<!-- sidebar-button: indicates that the enclosed text appears as a sidebar button in the application -->
<!ELEMENT sidebar-button (#PCDATA)>
<!-- tab: indicates that the enclosed text appears as a tab in the application -->
<!ELEMENT tab (#PCDATA)>
<!-- filter: indicates that the enclosed text is a mingle filter condition -->
<!ELEMENT filter (#PCDATA) >

=== Amit-Thawait/mingle/mingle/help/topics/viewing_project_changes.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE topic SYSTEM "mingle_help.dtd">
<topic title="Viewing project changes - History tab">
	<section title="Introduction">
		<p>Clicking the <tab>History</tab> tab lets you view changes made to a project over a specific period of time (by default all changes made today). 
    		It includes a complete audit log of all project changes which you can filter according to the information you want to see.</p>

		<bullets
			title="Different team members use the History tab differently according to the information they need">
			<item>project managers may want to see how much work is being completed and to see who has been working on different features or bugs</item>
			<item>testers or QAs may want to see which bugs were fixed yesterday</item>
			<item>developers may want to see what recent changes have been made to the source files</item>
			<item>business analysts may want to see progress or changes made to their user stories</item>
			<item>technical writers may want to see which help topics have been reviewed during the week.</item>
		</bullets>
		<hint>
    		Viewing the History tab is a great way to see the areas of the project you've been working on over a certain time. 
    		You can use this information for time sheets, project reviews, stand ups, or if you've forgotten the name of a card you were working on. 
    		Generally speaking, use the History tab if you know what you're looking for, or you know when you modified a card.
    		Otherwise use Mingle's <cref topic="mingle_search">search</cref>.
    	</hint>

		<p>The Filter history component in the top right lets you filter the exact changes you want to see. </p>

		<bullets title="The top section lets you select">
			<item>whether you want to view only changes to specific project elements (cards, wiki pages or code revisions)</item>
			<item>for cards, the specific properties they currently have or have acquired during the timeframe specified in the top History for: section (i.e. Today, Yesterday, Last 7 days, Last 30 days, In all history)</item>
			<item>specific tags that cards or wiki pages currently have or have acquired during the selected timeframe.</item>
		</bullets>

		<bullets
			title="The bottom section you can use in conjunction with the top section or on its own. It lets you select">
			<item>specific changes made to card properties within the selected timeframe</item>
			<item>specific tags that have been updated within the selected timeframe</item>
			<item>cards, wiki pages or code revisions made by specific people within the selected timeframe.</item>
		</bullets>
	</section>
	<section title="How to view project changes">
		<subsection title="By time" collapsed="true">
			<steps>
			<item>
	    		<p>Click the <tab>History</tab> tab.</p>
	    		<p>Mingle displays all changes made to the project during the last 24 hours (your local time).</p>
	    		<p><screenshot alttext="History tab" src="resources/images/history_tab_display.png" /></p>
	    	</item>
			<item>
	    		<p>If you want to view any project changes made longer than 24 hours ago, click a timeframe link at the top of the page.</p>
	    		<p>Mingle updates this page to include changes made during the time you specified.</p>
	    	</item>
			</steps>
		</subsection>
		<subsection title="By type" collapsed="true">
			<steps>
				<item><p>If you'd like to view specific project changes, select options in the Filter history at the right of the page.</p>
	    		<p>Mingle updates the History tab to display changes according to the filters you selected.</p>
				
		    	<bullets>
			    	 <item>If you'd like to include only changes made to cards, and/or wiki pages, and/or code revisions, select the checkbox(es) at the top of the Filter history component.</item>
				<p><screenshot alttext="View changes by types" src="resources/images/view_changes_by_types.png" /></p>    	
			    	 <item>If you'd like to view changes made to cards or wiki pages according to specific tags they currently have or have acquired during the timeframe you selected, click the Add tags link and type the tag name(s).</item>
		    	</bullets>
	    		<p><screenshot alttext="Add tags to filter history" src="resources/images/filter_history_add_tags.png" /></p>    	
	    		<p>Click the <button>Add tags</button> button to add them to the search filter.</p>
	    		</item>
			</steps>	
		</subsection>			

		<subsection title="By filter" collapsed="true">							
			<steps>
			<item>
	    		<p>If you'd like to view cards changed to a specific property value, or tags changed to a specific tag value within your selected timeframe, select filters from the bottom part of the Filter history component.</p>
	    		<p>You can select these on their own or in conjunction with the values you selected at the top part.</p>
	    		<screenshot alttext="Filter history" src="resources/images/filter_history.png" />
	    		<p>Mingle updates the History tab to display changes according to the filters you selected.</p>
	    	</item>
			<item>
				<p>With the 3.1 release, Mingle provides a new option, (any value), as a value in the history filter. If you select (any value) for any property listed in the history filter, you will be able to view any changes that have been made to that particular property.</p> 
				<note>This is especially helpful if you only want to know or be notified when a certain workflow you are interested in is changed. e.g. Story status, Bug status.</note>
	    		<screenshot alttext="(any value) in history" src="resources/images/any_value_in_history.png" />
			</item>
		    </steps>
		</subsection>
		<subsection title="By user" collapsed="true">
			<steps>	
			<item>
	    		<p>If you would like to view changes made by a specific team member, 
	    		select their name from the drop down menu at the bottom of the Filter history component.</p>
	    		<screenshot alttext="Filter history - changed by team member" src="resources/images/changed_by_team_member.png" />
				<p>Mingle updates the History tab to display changes made only by this team member.</p>
    		</item>
			<item>If you'd like to receive updates about project changes and events that occur based on the filters you've selected, you can subscribe via email or Atom feeds.</item>
			</steps>
			<hint>You can also select not set in conjunction with a card's changed value to see cards that went from not having a property value to acquiring one. </hint>
		</subsection>
	</section>
	<section title="Subscribing to project changes">    	
    	<p>In the bottom-right of the History tab is a <sidebar-button>Watch this?</sidebar-button> component. 
    		Here you can subscribe via email or Atom feeds to changes made in the project based on the information currently displayed on the screen (i.e. based on the filters you've selected).</p>
    	<bullets>
	    	 <item><cref topic="subscribing_via_feeds">Subscribing to project changes via Atom feeds</cref></item>
	    	 <item><cref topic="subscribing_via_email">Subscribing to project changes via email</cref></item>
    	</bullets>
    </section>
</topic>

=== Amit-Thawait/mingle/mingle/help/topics/tip_tagging_on_wiki_pages.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE section SYSTEM "mingle_help.dtd">
<chapter title="Apply tags to pages">
	<p>You can enhance management of your pages by tagging them. Tagging pages allows you to access any page you're looking for quickly and easily. </p>
	<section title="Tagging pages">
		<p>Tagging is available on the top of every page, just like <cref topic="creating_tags_for_cards_or_pages">tagging on cards</cref>. </p>
  		<steps>
  		  <item>To tag a page select "edit tags"</item>
  		  <item>Type in your tag or choose from the options available</item>
  		  <item>The page is now tagged</item>
  		  <p><screenshot alttext="tagging on wiki" src="resources/images/tag.png"/></p>
  		  </steps>
	</section>
<section title="Using tags to find pages">
	<steps>
	  <item>In the Mingle search field, type in the tag to find the page you're looking for. </item>
	  <p><screenshot alttext="using tag for search" src="resources/images/use_tag_for_search.png" /></p>
	  <item>Only pages and cards that have this tag will be returned as a result.</item>
		<p><screenshot alttext="search result" src="resources/images/find_page_tagged_with.png" /></p>
		</steps>
		</section>
</chapter>

=== Amit-Thawait/mingle/mingle/help/topics/card_property_values_page.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE topic SYSTEM "mingle_help.dtd">
<topic title="Card property values page">
	<warning>Card property values determine how Mingle manages project workflow. 
		Adding or changing property values may have a major impact on the project team. 
		Ensure you understand the details in <cref topic="card_properties">card properties</cref> before changing values on this page.</warning>
	<section title="What you can do on this page">
		<p>The Card property values page lets you <cref topic="maintain_card_property_values">add, edit or delete the values</cref> 
			available for <cref topic="card_property_types">managed list card properties</cref>, and shows how many cards share the value. 
			From here you can change the colors assigned to values and re-order the list of values by dragging and dropping. 
			The order of the property values determines how cards display when Sorting in the <cref topic="grid_view">Grid view</cref>.</p>
		
		<p>You can also use the <link>Edit property</link> link to <cref topic="modifying_or_deleting_card_properties">modify the card property</cref> itself</p>.
		<bullets>
			<item><cref topic="maintain_card_property_values">Maintaining card property values</cref></item>
			<item><cref topic="card_properties">Card properties overview</cref></item>
			<item><cref topic="card_property_types">Card property types</cref></item>
			<item><cref topic="creating_card_properties">Creating card properties</cref></item>
			<item><cref topic="modifying_or_deleting_card_properties">Modifying or deleting card properties</cref></item>
		</bullets>
	</section>
		<section title="Also see...">
			<bullets>
				<item><cref topic="card_transitions">Card transitions</cref></item>
				<item><cref topic="card_defaults">Card defaults</cref></item>
				<item><cref topic="project_variables">Project variables</cref></item>
			</bullets>
		</section>		
</topic>

=== Amit-Thawait/mingle/mingle/help/topics/automated_transitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE chapter SYSTEM "mingle_help.dtd">
<chapter title="Automated card transitions">

<section title="Introduction">
<p><cref topic="card_transitions">Card transitions</cref> and <cref topic="transition_only_properties">transition only properties</cref> are a very useful way for project administrators to enforce a project workflow. Likewise, card walls and the Mingle <cref topic="grid_view">grid view</cref> are useful ways for an Agile project team to easily visualize and update the status of cards in their project.</p>
<p>Automated transitions combine the card wall concept to update card status, as provided in Mingle's grid view, with the workflow enforcement provided by card transitions. Simply, automated transitions allow the team to update and view their project status quickly while also ensuring other important data is captured.</p> 
</section>

<section title="Why do I need automated transitions?"> 
<p>A common example of a status update that happens frequently and needs to be efficient is the story wall status update. This update also often requires extra reporting data to be captured which is not provided by using the grid view alone.</p>
<p>Consider a standard story wall that is tracking the status of stories in a given release or iteration. Generally this wall is divided into status lanes that indicate the current state of stories in the project (e.g. 'ready for development', 'in development' and 'closed'). In the simplest scenario, team members will move cards from one state to another as the project progresses. The <cref topic="grid_view">grid view</cref> is a good way to represent this scenario in Mingle. However, for projects that require tracking and reporting information (such as the date a story moved between states), Mingle transitions need to be used to ensure the tracking information is provided at the same time the status is updated.</p>
<p>Transition only properties are one way to ensure values are only updated using the transitions and therefore, ensure that supplementary tracking information is also updated. Using transition only properties in transitions previously meant that the ease of movement on the grid view was restricted to enforce the workflow. This is where automated transitions bridge that gap: they allow quick update of cards properties using the grid view but also ensure any required data and workforce is achieve by triggering transitions when cards are moved in the grid.</p>
</section>

<section title="What is needed to automate transitions on grid view?">

<p>To automate transitions on the grid view project admins will need to ensure they have the required transitions set-up and that these transitions are updating transition only properties. They can then group by the transition only property on the grid view and any card movements between states that match a transition will trigger the transition to be automated. For example, to create the automated story wall the admin would need to complete the following steps:</p>

<steps>
<item>Create a <cref topic="card_types">card type</cref> called 'story'</item>
<item><cref topic="creating_card_properties">Create a card property</cref> called 'status' with values of 'in development' and 'closed' 
</item>
<item>Set 'status' property as transition only</item> 
	<screenshot alttext="Set property as transition only" src="resources/images/auto_transition_property_transition_only.png"/> 
<item>Create a reporting property called 'Development complete on'</item>
<item>Create transitions that updates stories which are 'in development' to status 'closed' and sets the 'Development complete on' as today</item>
 <screenshot alttext="Create transition" src="resources/images/auto_transition_transition.png"/>
<item> Create a grid view and filter cards by 'story' type and group by property 'status'. This is the story wall:</item>
	<screenshot alttext="Create story wall" src="resources/images/auto_transition_story_wall.png"/> 
<item> Move stories between the 'in development' column and the 'closed' column</item>
	<screenshot alttext="Trigger transition" src="resources/images/auto_transition_drag_card.png"/> 
<item> The transition is triggered
	
	<p>	<screenshot alttext="Transition is completed" src="resources/images/auto_transition_complete.png"/> </p>
	The stories are automatically updated with the 'Development complete on'
	<p>	<screenshot alttext="Card properties are updated" src="resources/images/auto_transition_properties_updated.png"/> </p>
	
</item>
</steps>
 </section>

<section title="Why weren't my cards updated?">
<bullets><item><strong>Transitions will only be automated on the grid view</strong> - for Mingle and projects admins, who can update transitions only properties in other views, any updates not made on the grid view will not automate transitions. </item>

<item><strong>Property updates can only be automated if transitions are created</strong> - for example, although a transition may have been created to update cards with 'in development' to 'development complete' the reverse transition may not have been created. In this instance if the cards are dragged in the reverse direction to 'in development' from 'development complete' then an update will not be made and the user will be informed. 

	<p>	<screenshot alttext="Card properties are updated" src="resources/images/auto_transition_no_transition.png"/> </p>
</item>

<item><strong>Property updates can only be automated if the group by property on the grid view is transition only </strong> - if transitions are created to update properties that are not transition only then dragging and dropping cards to update this property value will not automate transitions. These properties can be updated independently and do not require transitions to be updated. 
</item>

</bullets>
	
</section>

<section title="How to..."> 

<bullets>
    <item><cref topic="creating_card_transitions">Create card
    transitions</cref></item>

    <item><cref topic="modifying_or_deleting_card_transitions">Modify or
    Delete card transitions</cref></item>

    <item><cref topic="transition_only_properties">Apply transition only
    properties</cref></item>
 
  </bullets> </section> <section title="Also see..."> <bullets>

<item><cref topic="card_transitions">About card transitions </cref></item>
    <item><cref topic="card_properties">About card properties</cref></item>

    <item><cref topic="customizing_projects">Customizing
    projects</cref></item>
  </bullets> 
</section>
</chapter>
