=== Amit-Thawait/mingle/mingle/help/topics/mingle_help.dtd
<!--
/*
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
*/
			INDEX - for building the left nav control
-->
<!ELEMENT index (#PCDATA | entry)* >
<!ELEMENT entry (#PCDATA | entry)* >
<!ATTLIST entry reference CDATA #REQUIRED >

<!-- 
            TAGS WHICH ARE USED TO FORMAT THE HELP PAGES
-->
<!ELEMENT chapter (#PCDATA | topic | section)* >
<!ATTLIST chapter title CDATA #REQUIRED>

<!ELEMENT topic (#PCDATA | section | p | note | hint | warning | bullets | steps | markup_reference | screenshot | todo | img | example | config | code | markup | formula | api_reference | table)*>
<!ATTLIST topic title CDATA #REQUIRED>
<!ATTLIST topic file CDATA #IMPLIED>
<!ATTLIST topic collapsed CDATA #IMPLIED>

<!ELEMENT section (#PCDATA | subsection | p | note | hint | warning | bullets | steps | markup_reference | screenshot | todo | img | example | config | code | markup | formula | api_reference | table)*>
<!ATTLIST section title CDATA #REQUIRED>
<!ATTLIST section file CDATA #IMPLIED >
<!ATTLIST section collapsed CDATA #IMPLIED>

<!ELEMENT subsection (#PCDATA | p | note | hint | warning | bullets | steps | markup_reference | api_reference |screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | table)*>
<!ATTLIST subsection title CDATA #REQUIRED>
<!ATTLIST subsection file CDATA #IMPLIED >
<!ATTLIST subsection collapsed CDATA #IMPLIED>

<!ELEMENT table (#PCDATA | group | header-row | row )* >
<!ATTLIST table caption CDATA #REQUIRED >

<!ELEMENT group (#PCDATA | row )* >
<!ATTLIST group title CDATA #REQUIRED >
<!ATTLIST group col-headers CDATA #IMPLIED >

<!ELEMENT header-row (#PCDATA | col-header)*>
<!ELEMENT col-header (#PCDATA) >

<!ELEMENT row (#PCDATA | label | col)* >
<!ELEMENT label (#PCDATA) >
<!ELEMENT col (#PCDATA | p | bullets | steps | screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | filter )* >

<!-- markup_reference - is a reference entry to explain some markup.
        it contains a title to explain the intent,
        a markup element to show the markup,
        a preview to show the outcome of the markup,
        a note (optional),
        an icon (optional) - e.g. the toolbar icon for example that will insert the markup -->
<!ELEMENT markup_reference ( markup | preview | note | icon | todo)*>
<!ATTLIST markup_reference title CDATA #REQUIRED>

<!ELEMENT api_reference ( code | preview | note | bullets )* >
<!ATTLIST api_reference title CDATA #REQUIRED>

<!ELEMENT steps ( p | item+)*>
<!ATTLIST steps title CDATA #IMPLIED>

<!ELEMENT bullets ( p | item+)*>
<!ATTLIST bullets title CDATA #IMPLIED>

<!ELEMENT item (#PCDATA | p | note | hint | warning | bullets | steps | screenshot | strong | cref | exref | todo | img | example | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | formula | filter )*>

<!ELEMENT screenshot (#PCDATA)>
<!ATTLIST screenshot alttext CDATA #REQUIRED>
<!ATTLIST screenshot src CDATA #REQUIRED>
<!ATTLIST screenshot caption CDATA #IMPLIED>

<!ELEMENT cref (#PCDATA)>
<!ATTLIST cref topic CDATA #REQUIRED>

<!ELEMENT strong (#PCDATA | todo | link | button | sidebar-button | cref | cmd)*>

<!ELEMENT p (#PCDATA | exref | strong | cref | img | screenshot | video | todo | term | link | button | sidebar-button | tab | cmd | code | path | markup | url | subst | filter | formula | config | table)*>

<!ELEMENT exref (#PCDATA)>
<!ATTLIST exref url CDATA #REQUIRED>

<!ELEMENT hint (#PCDATA | p | strong | cref | exref | todo | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula | bullets)*>
<!ELEMENT note (#PCDATA | p | strong | cref | exref | todo | example | bullets | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula)*>
<!ELEMENT warning (#PCDATA | p | strong | cref | exref | todo | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula | bullets)*>

<!ELEMENT example (#PCDATA | p | strong | cref | exref | todo | bullets | steps | img | screenshot | term | link | button | sidebar-button | tab | cmd | config | code | path | markup | url | subst | filter | formula)*>
<!ATTLIST example title CDATA #IMPLIED>

<!ELEMENT img (#PCDATA | clickaction)*>
<!ATTLIST img alttext CDATA #REQUIRED>
<!ATTLIST img src CDATA #REQUIRED>
<!ATTLIST img url CDATA #IMPLIED>

<!-- icon refers to a UI element, and holds a picture of that element -->
<!ELEMENT icon (#PCDATA)>
<!ATTLIST icon alttext CDATA #REQUIRED>
<!ATTLIST icon src CDATA #REQUIRED>

<!-- clickaction is used to map links to clickable areas inside an image -->
<!ELEMENT clickaction (#PCDATA | exref | cref)*>
<!ATTLIST clickaction align CDATA #REQUIRED>
<!ATTLIST clickaction unit CDATA #REQUIRED>
<!ATTLIST clickaction height CDATA #REQUIRED>
<!ATTLIST clickaction width CDATA #REQUIRED>
<!ATTLIST clickaction offset CDATA #IMPLIED>

<!-- video refers to a link to some video content, allows decoration with an appropriate icon -->
<!ELEMENT video (#PCDATA)*>
<!ATTLIST video url CDATA #REQUIRED>

<!-- cmd: indicates that the enclosed text is an operating system command -->
<!ELEMENT cmd (#PCDATA | p)*>
<!ATTLIST cmd os CDATA #IMPLIED>
<!-- config: indicates that the enclosed text is a piece of application configuration -->
<!ELEMENT config (#PCDATA)*>
<!-- code: indicates that the enclosed text is a piece of programming language source code -->
<!ELEMENT code (#PCDATA | strong | cref | subst)*>
<!ATTLIST code lang CDATA #IMPLIED>
<!-- path: indicates that the enclosed text is a path to a file -->
<!ELEMENT path (#PCDATA | subst)*>
<!-- markup: indicates that the enclosed text is markup -->
<!ELEMENT markup (#PCDATA | subst | todo)*>
<!-- preview: indicates that the enclosed text is preview of markup -->
<!ELEMENT preview (#PCDATA | p | img | screenshot | todo | code)* >
<!-- url: indicates that the enclosed text is an url - note this is a formatting tag, the url should not be navigable -->
<!ELEMENT url (#PCDATA | subst)*>
<!-- subst: indicates that the enclosed text should be substituted with another value (or removed) -->
<!ELEMENT subst (#PCDATA) >
<!-- todo - indicates that something need to be changed or added to the content at this point, should not appear in final help output -->
<!ELEMENT todo (#PCDATA)*>
<!-- term: indicates that the enclosed text should appear in the glossary -->
<!ELEMENT term (#PCDATA)>
<!-- formula: indicates that the enclosed text is a formula -->
<!ELEMENT formula (#PCDATA | subst | todo)*>

<!-- 
        TAGS THAT REFER TO APPLICATION WIDGETS
-->
<!-- link: indicates that the enclosed text appears as a link in the application -->
<!ELEMENT link (#PCDATA)>
<!-- button: indicates that the enclosed text appears as a button in the application -->
<!ELEMENT button (#PCDATA)>
<!-- sidebar-button: indicates that the enclosed text appears as a sidebar button in the application -->
<!ELEMENT sidebar-button (#PCDATA)>
<!-- tab: indicates that the enclosed text appears as a tab in the application -->
<!ELEMENT tab (#PCDATA)>
<!-- filter: indicates that the enclosed text is a mingle filter condition -->
<!ELEMENT filter (#PCDATA) >

=== Amit-Thawait/mingle/mingle/help/topics/installing_mingle_on_windows.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE chapter SYSTEM "mingle_help.dtd">
	<section title="How to install Mingle for Windows" collapsed="true">
		<note>You must be logged in as a user with Admin privileges to install the Mingle service under Windows.</note>
		<subsection title = "Installing Mingle for the first time" collapsed="false">
		<steps>			
			<item>Double-click the Mingle installer file and follow the prompts to install Mingle.</item>
			<item>
				<p>During installation, Mingle will ask you to:</p>		
				<bullets>
				  <item>select a destination directory. This is where Mingle will be installed.</item>
					<item>select a data directory to store data. This is where Mingle will store project data including configuration files and attachments. It is not the database location.</item>
					<item>select a swap directory to store temporary data. This will act as a tmp space in which to store intermediate data such as project exports (.mingle files) while they are being created, project import files that are being imported, excel import content that is being processed for preview and excel import content that is being processed for import.</item>
					<item>select a config directory to store configuration data. This is where Mingle will store project configuration files such as database.yml. This is not the database location.</item>
					<item>select a port from which to run Mingle. The default for this is '8080' but you can set it to any port that is not currently being used.</item>
				</bullets>
				<hint>If you have previously installed Mingle in the selected destination directory, all Mingle files from the existing instance will be deleted <strong>except</strong> log files, cache and any contents in /vendor/plugins.</hint>
			</item>
			<item>
				<p>At the end of the installation, Mingle opens the <cref topic="completing_the_mingle_configuration_wizard">configuration wizard</cref> in your default web browser.</p>
				<screenshot alttext="Welcome to Mingle" src="resources/images/installation/setup_wizard.png" />
			</item>
			<item>	If you have issues starting Mingle please refer to Mingle's <cref topic="troubleshooting_mingle_installation_and_upgrade">troubleshooting help</cref>.</item>
		</steps>
		</subsection>
		
		<subsection title="Installing Mingle when there is an existing installation of Mingle" collapsed="true">
		 <p>Beginning with 2.3, Mingle allows the user to follow the Mingle installation process without restarting the computer even if Mingle is already installed. When you install the same or a newer version of Mingle at the same location as an existing installation of Mingle, the existing installation will be uninstalled before the new version is installed.</p>
		 <steps>
		 	<item>If any version of Mingle is already installed and is currently running, the server will be stopped and the existing installation of Mingle with be uninstalled.</item>
		   	<item>If any version of Mingle is already installed but the server is not running, the existing installation of Mingle with be uninstalled.</item>
		   	<item><p>Uninstalling Mingle involves deleting all Mingle related files <strong>except</strong>:</p>
			  <bullets>
				<item>The all contents of the data directory (and the database used)</item>
				<item>The config directory</item>
				<item>The swap directory</item>
				<item>The installation folder log directory - contains all mingle log files</item>
				<item>The /vendor/plugins directory - contains any custom plugins (if there are any)</item>
				<item>The installation folder tmp directory - contains temporary files and cache</item>
			  </bullets>
			</item>
		 </steps>
		
		</subsection>
		</section>

=== Amit-Thawait/mingle/mingle/help/topics/setup_perforce_configuration.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE section SYSTEM "mingle_help.dtd">
<section title="Perforce source integration for Mingle Onsite">
  <subsection title="Before you start">
  <note>
    <item>Native Perforce integration is available for Mingle onsite only.</item>
    <item>Before you can configure Perforce as your source repository please ensure the Perforce command line client, <exref url="http://www.perforce.com/perforce/products/p4.html">"p4"</exref>, is installed on the machine running Mingle.</item>
  </note>
  
  <note>If you are unable to use Perforce because Mingle cannot locate "p4" please update perforce_config.yml in the Mingle config directory. If you are unable to locate perforce_config.yml in your config directory, selecting Perforce as the version control system should create this file. </note>
</subsection>
	<subsection title="Configuration">
  <p>After successfully choosing <strong>Perforce</strong> from the source repository list, Mingle will display the <strong>Perforce Repository settings</strong> page.</p>
  <screenshot alttext="Perforce Repository settings page" src="resources/images/perforce_repository_settings_page.png" />

  <bullets>
    <item>Enter the depots that you wish to connect to. If you have multiple depot paths, separate each path with a space.</item>
    <item>Enter the hostname or ip address of the Perforce server</item>
    <item>Enter the port of the Perforce server</item>
    <item>Enter the username/password to connect to the Perforce server. You must first click the <button>Change login user password</button> to enter a new password.</item>
    
    <screenshot alttext="Perforce repository settings page - user password" src="resources/images/perforce_repository_settings_password.png" />
    
    <item>Click the <link>Save settings</link> link to save the configuration and return to the <strong>Project admin</strong> page</item>  
  </bullets>
</subsection>
</section>

=== Amit-Thawait/mingle/mingle/help/topics/whats_new_in_release_12_1.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE topic SYSTEM "mingle_help.dtd">
<topic title="What's new in Release 12.1">
  <p>Please review the <cref topic="upgrading_from_previous_versions">upgrade instructions</cref> before moving to Mingle 12.1.</p>
  <section title="A new release naming convention">
    <p>Starting with this release, Mingle has jumped to a new release number. This change was made to follow ThoughtWorks Studios' new release naming convention. We will continue to use the major.minor.bugfix nomenclature, but the major version will now be the year of the release (e.g. 12) and the minor version will indicate the release in that year (e.g. 12.3 will be the third release in 2012).</p>
  </section>
  <section title="Daily history chart with forecasting">
    <p>The daily history chart has been enhanced to allow teams to <cref topic="charts#forecasting_chart">forecast</cref> when they may be complete based on their current velocity and different scope change scenarios. It will now display a trend line that forecasts when the team may be done if their remaining scope remains constant, increases by 50% or increases by 150%.</p>
	<screenshot src="resources/images/charts_forecasting_daily_history_chart_example.png"/>
  </section>
  <section title="Daily history chart with fixed date delivery">
    <p>Conversations focused on forecasting are commonplace in software delivery. Equally common are conversations regarding <cref topic="charts#fixed_date_chart">fixed date</cref> and variable scope. To aid this scope management scenario, the daily history macro also provides the ability to show a chart that highlights the amount of scope that may need to be reduced in order to meet a target release date.</p>
	<screenshot src="resources/images/charts_fixed_date_daily_history_chart_example.png"/>
  </section>
  <section title="Collaboration Improvements: See who's viewing the same card or page as you">
    <p>Mingle will now tell you who else on your team is <cref topic="collaborating_with_wiki_pages">viewing or editing</cref> the card or page you are looking at. This feature has already provided us with many more opportunities to have a conversation just by telling us who else is viewing the cards we are working with.</p>
    <screenshot src="resources/images/also_viewing.png"/>
  </section>
  <section title="TFS source repository integration">
    <p>We strive to provide an open product suite that integrates with a variety of development ecosystems. The newest addition to our supported ecosystem will be <cref topic="setup_tfs_configuration">Team Foundation Server (TFS)</cref>. Mingle 12.1 will support TFS as a source repository. Take a look at our ThoughtWorks Studios blog for other ways our products integrate with the Microsoft Ecosystem.</p>
  </section>
  <section title="Search improvements">
    <p>Mingle 12.1 includes a new <cref topic="mingle_search">search</cref> engine and introduces changes to the search results layout to help provide more relevant and clearer search results. You can now filter your search results by cards, wiki pages or murmurs. The new search engine allows us to deliver more frequent search enhancements in the future and we'll continue to tweak the engine and the results layout to make it easier for you to find what you're looking for.</p>
  </section>
</topic>

=== Amit-Thawait/mingle/mingle/help/topics/setup_github_configuration_saas.xml
<?xml version="1.0"?>
<!--
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-->
<!DOCTYPE section SYSTEM "mingle_help.dtd">
<section title="GitHub integration for Mingle in the Cloud" id="github_saas">
  
  <p>The following instructions outline how to integrate your GitHub repo with your Mingle in the cloud project. You can integrate multiple GitHub repos to a single project and connect a single GitHub repo to multiple projects.</p>
  <note>
    <bullets>
      <item>This integration allows your GitHub commits to be pushed as <cref topic="murmurs">Murmurs</cref> to your Mingle project and, when you mention the card number in your commit message, the individual card as well.</item>
      <item>The commit murmured to your Mingle project will contain a link back to your GitHub repo so you can see commit details and diffs.</item>      
      <item><strong>TIP</strong>: If you <cref topic="murmurs">murmur</cref> at an existing team member (e.g. @user) in your Git commit message that person will also receive an email notification.</item>
      <item>You can integrate multiple GitHub repos to a single project and connect a single GitHub repo to multiple projects, but you must integrate one repo to one project at a time.</item>
      <item>If you’re connecting a single repo to multiple projects, make sure your commit message includes the project id along with the card number (e.g. project_A/#123 or project_B/#123), otherwise the commit will be murmured to the same card number in all of your projects. Use <exref url="/mingle/news/2014/04/18/Clippy.html">Clippy</exref> to help out with this.</item>
    </bullets>
  </note>    
    <subsection title="Requirements">
      <bullets>
        <item>Only users who are both Mingle admins and <exref url="https://help.github.com/articles/what-are-the-different-access-permissions">owners of the GitHub repo</exref> can setup the integration with the Mingle project</item>
      </bullets>  
    </subsection>

    <subsection title="Steps">
      <steps>
        <item>Open your Mingle project</item>
        <item>Got to <strong>Project Admin</strong></item>      
        <item>Under <strong>Code Integration</strong> select <strong>GitHub</strong></item> 
        
              <screenshot alttext="avatars_on_the_wall" src="resources/images/github_code_integration.png"/>
             
        <item><strong>Complete the form</strong> with your GitHub information</item> 
        <item>Click<strong>"Connect to GitHub"</strong></item>
        
                <screenshot alttext="avatars_on_the_wall" src="resources/images/github_connect_form.png"/>
           
      </steps>
      <note>If you create webhooks directly from your GitHub account, they will not be listed in Mingle. You must create the webhook from Mingle in order for it to be listed.</note>	
    </subsection>

    <subsection title="GitHub personal API token">
      <steps>
        <item>Learn more about GitHub personal API token <exref url="https://github.com/blog/1509-personal-api-tokens">here</exref></item>
        <item>Sign in to GitHub</item>      
        <item>Go to <strong>Edit Profile</strong></item>      
        <item>Select <strong>Applications</strong></item> 
        
                <screenshot alttext="avatars_on_the_wall" src="resources/images/github_applications.png"/>
        
        <item>Click <strong>Generate New Token</strong></item>   
        
                <screenshot alttext="avatars_on_the_wall" src="resources/images/github_generate_new_token.png"/>
                
        <item><strong>Name token</strong></item>     
        <item>Click <strong>Generate token</strong></item>   
        
                <screenshot alttext="avatars_on_the_wall" src="resources/images/github_generate_token.png"/>
        
        <item>Copy token to clipboard (<strong>Note:</strong> Once you’ve navigated away from this page you will no longer be able to view the token and will need to regenerate the token)</item>
        
              <screenshot alttext="avatars_on_the_wall" src="resources/images/github_copy_to_clipboard.png"/>
             
        <item>Paste this token in the corresponding Mingle field (see above)</item>   
      </steps>
    </subsection>

    <subsection title="Test your Git Integration">
      <steps>
         <item>Push a commit to the GitHub repo you just added the webhook to</item>
         <item>Go to the Murmurs tab in the Mingle project associated with the webhook</item>     
         <item>You should see a recent Murmur, like this:</item>
         
          <screenshot alttext="avatars_on_the_wall" src="resources/images/github_murmur.png"/>
         
         <item>If you pushed a commit that referenced a specific card, you should also see the commit murmured on the individual card sidebar as well:</item>
         
         <screenshot alttext="avatars_on_the_wall" src="resources/images/github_card.png"/>
        </steps>        
    </subsection>
	<subsection title="Deleting Webhooks">
		<p>You currently cannot delete webhooks from Mingle. You must delete them from your GitHub account. (N.B. For the time being, even if you delete the webhook from your GitHub account, it will still be listed on the GitHub integration page in your Mingle project.)</p>
	</subsection>	
</section>
